version: '1'
services:
  notebook:
    build: .
    entrypoint:
      - jupyter
      - lab
      - --ip=0.0.0.0
      - --allow-root
      - --no-browser
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks/local_notebooks
      - /mnt/lab/users/josue/notebooks:/notebooks/lab_notes
      - /mnt/scratch07:/external
