version: '3'
services:
  notebook:
    build: .
    entrypoint:
      - jupyter
      - lab
      - --ip=0.0.0.0
      - --allow-root
      - --no-browser
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks/local_notebooks
